"""add credit tables

Revision ID: 1f4b51903943
Revises: 004
Create Date: 2026-08-02 16:17:59.134021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4b51903943'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('credit_limit', sa.BigInteger(), nullable=False),
    sa.Column('available_credit', sa.BigInteger(), nullable=False),
    sa.Column('used_credit', sa.BigInteger(), nullable=False),
    sa.Column('reserved_credit', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_index('ix_credit_accounts_agent_id', 'credit_accounts', ['agent_id'], unique=False)
    op.create_index('ix_credit_accounts_owner_id', 'credit_accounts', ['owner_id'], unique=False)
    op.create_table('credit_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('score', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_limit', sa.BigInteger(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_decisions_agent_id', 'credit_decisions', ['agent_id'], unique=False)
    op.create_table('repayment_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_account_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('paid_amount', sa.BigInteger(), nullable=False),
    sa.Column('repayment_method', sa.Text(), nullable=False),
    sa.Column('provider_transaction_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repayment_schedule_account_id', 'repayment_schedule', ['credit_account_id'], unique=False)
    op.create_index('ix_repayment_schedule_due_date', 'repayment_schedule', ['due_date'], unique=False)
    op.create_index('ix_repayment_schedule_status', 'repayment_schedule', ['status'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credit_account_id', sa.UUID(), nullable=False),
    sa.Column('payout_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_accounts.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_transactions_account_id', 'credit_transactions', ['credit_account_id'], unique=False)
    op.create_index('ix_credit_transactions_created', 'credit_transactions', ['created_at'], unique=False)
    op.create_index('ix_credit_transactions_type', 'credit_transactions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_transactions_type', table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_created', table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_account_id', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('ix_repayment_schedule_status', table_name='repayment_schedule')
    op.drop_index('ix_repayment_schedule_due_date', table_name='repayment_schedule')
    op.drop_index('ix_repayment_schedule_account_id', table_name='repayment_schedule')
    op.drop_table('repayment_schedule')
    op.drop_index('ix_credit_decisions_agent_id', table_name='credit_decisions')
    op.drop_table('credit_decisions')
    op.drop_index('ix_credit_accounts_owner_id', table_name='credit_accounts')
    op.drop_index('ix_credit_accounts_agent_id', table_name='credit_accounts')
    op.drop_table('credit_accounts')
    # ### end Alembic commands ###
